### ISSUE TITLE
Support CMD specification

### ISSUE THREAD

**Issue by blue68** [gruntjs/grunt-contrib-jade#102]
I have here a demand, front-end js use sea.js, module specifications using CMD, using js compiled after the grunt AMD specification is not supported CMD specification

**Comment by shinnn** [comment]
Probably @blue68 referred to https://github.com/cmdjs.

We won't support it since [its specification is still draft](https://github.com/cmdjs/specification/tree/3ec033e973738295d284c00cdf448d29210984dd/draft) and seems to be abandoned now.
