### ISSUE TITLE
Support caching

### ISSUE THREAD

**Issue by ForbesLindesay** [gruntjs/grunt-contrib-jade#107]
Could you support caching in some way?  Perhaps using something like #74?  I maintain jade and get many issues such as https://github.com/visionmedia/jade/issues/1581 where people are struggling with performance of compilation.  This is usually the result of compiling a small number of templates many times (once per page where each page has different data but the same template).  I think that if this module supported caching, people would not struggle with this issue.

**Comment by miguelmich** [comment]
I would love this :)

**Comment by brunowego** [comment]
+1
