### ISSUE TITLE
Error with generated AMD client template module

### ISSUE THREAD

**Issue by andrewnida** [gruntjs/grunt-contrib-jade#111]
I am attempting to use compiled AMD templates with runtime.js within requirejs. I keep getting the error: "Uncaught TypeError: undefined is not a function" in the minimized javascript file using the template as a dependency.

I noticed in the compiled template file that "jade" was being used as a dependency and checking for the "runtime" property as a member of the jade dependency:
"define(['jade'], function(jade) { if(jade && jade['runtime'] !== undefined) { jade = jade.runtime; }"

By swapping out the "jade" dependency and replacing with "runtime", I was able to resolve the error and templates seem to be functioning normally.
"define(['runtime'], function(runtime) { if(runtime && runtime !== undefined) { jade = runtime; }"

Is this an issue within the jade task in grunt-contrib-jade, or am I setting up the dependencies incorrectly within my requirejs module?

I'm glad I was able to move past this issue, but I am curious if there is a better solution or something obvious I'm missing.

**Comment by ajarbol** [comment]
+1
