### ISSUE TITLE
extra . causes template to silently render to empty string

### ISSUE THREAD

**Issue by rfarris** [gruntjs/grunt-contrib-jade#122]
I upgrade grunt-contrib-jade from 0.10 to 0.13 and some of my templates started quietly rendering to empty strings.  No errors or warnings. (Ironically, we upgraded for the .12 change that fails on errors)

Given a jade file with the contents:

    blockquote. Test

The rendered html file will be empty.  No errors will be logged. Removing the `.` will cause it to render the blockquote.

I assumed it was a jade issue, but Jade 1.7.0 by itself renders the blockquote just fine with and without the extra `.`

Edit: I should note that if there is a like line this _anywhere_ in the template, the _entire_ template renders to an empty string.

**Comment by shinnn** [comment]
http://jade-lang.com/reference/plain-text/

Check *Block in a Tag* section.
