### ISSUE TITLE
Support for CommonJS wrapper

### ISSUE THREAD

**Issue by monolithed** [gruntjs/grunt-contrib-jade#123]
I need an alternative to export modules like the LMD/CommonJS wrapper

```js
module.exports = function (template) {
   return template;
};
```

or the `process` option to do any custom processing before like

```js
module.exports = function (grunt) {
    var done = this.async();

    grunt.initConfig({
        jade: {
            process: function (src, path) {
                return 'module.exports = function () { return ' + src + '};'
            }
        }
    });
};
```

**Comment by shinnn** [comment]
[LMD is no longer supported.](https://github.com/azproduction/lmd/tree/03410c36839728de683c697670e1b205dc8193ee#warning-project-is-no-longer-supported)
