### ISSUE TITLE
how to pass function to jade?

### ISSUE THREAD

**Issue by fuddl** [gruntjs/grunt-contrib-jade#131]
I'd like to pass this function to jade:

```js

function foo() {
  return 'bar';
}

```

so I can call it, writing:

```jade
h1
  - foo();
```

expected result:

```html
<h1>foo</h1>
``` 
how can I do this without actually writing this function into the jade file?

**Comment by shinnn** [comment]
Questions go to http://stackoverflow.com/questions/tagged/gruntjs Thanks!
