### ISSUE TITLE
Grunt-jade, express.js and i18n

### ISSUE THREAD

**Issue by pagoad** [gruntjs/grunt-contrib-jade#135]
I use Grunt, Jade and express.js.

In my jade template i Use i18n - https://github.com/mashpie/i18n-node/

like this:

> span #{__('agency')}

When i start grunt serve it is ok, it works excellent. But if i want to compile it grunt-jade tell me that

> span #{__('agency')}
undefined is not a function

I have no idea what to do.

**Comment by shinnn** [comment]
Check [grunt-jade-i18n](https://github.com/AdesisNetlife/grunt-jade-i18n). Maybe it meets your requirements.

**Comment by pagoad** [comment]
Thx!
Could you tell me how in grunt-jade i could define internationalization like this:

>#{__('agency')}

not like:

> #{$i18n.agency}

Because i18n in express js define it in different way.

**Comment by shinnn** [comment]
If you want to use an external function in the templates, pass it via [`data` option].

Example:

```js
options: {
  data: {
    __: require('what-you-want-to-use')
  }
}
```

**Comment by pagoad** [comment]
Hmm...
I think i dont understand how to use it correctly :/
