### ISSUE TITLE
Using lodash (or any other node modules) with Jade tempate.

### ISSUE THREAD

**Issue by saneef** [gruntjs/grunt-contrib-jade#136]
Is it possible to access lodash (or any other node modules) with in a Jade template.

Here is an use case I need to use
```jade
- userNames = _.pluck(users, 'user');
ul
  each name in userNames
  li= name
```

**Comment by vladikoff** [comment]
https://github.com/gruntjs/grunt-contrib-jade/issues/131#issuecomment-71883279
