### ISSUE TITLE
option to always include a set of files

### ISSUE THREAD

**Issue by loominade** [gruntjs/grunt-contrib-jade#140]
is there a way to include files to each compiled file?

```js
options: {
  require: ['common/mixins.jade', 'common/functions.jade']
  data: …
}
```

**Comment by shinnn** [comment]
You can add `+common/mixins.jade\n+common/functions.jade\n` to every file with [grunt-contrib-concat](https://github.com/gruntjs/grunt-contrib-concat).

**Comment by shinnn** [comment]
@loominade By the way, why you create two accounts, Müller? @fuddl

**Comment by loominade** [comment]
one of it is private, one is professional
