### ISSUE TITLE
How do I compile mutliple HTML Jade templates that use the same mixin

### ISSUE THREAD

**Issue by AJeezy9** [gruntjs/grunt-contrib-jade#141]
mixin hero(title)
		.hero
			.hero__inner
				h1.hero__title #{title}

So, my project uses a Jade mixin like the above on multiple pages and, when I compile the Jade to HTML pages, I have to copy that mixin on each page that it is used.

Can this module be used to globally pass that mixin to all pages so I don't have to copy it everytime? 

It would make my life 1000x easier.

**Comment by shinnn** [comment]
[processContent](https://github.com/gruntjs/grunt-contrib-jade/tree/0768aa72e9ae3fc61dd52650d5f02f503e4c3fb3#processcontent) option helps you.

```js
jade: {
  compile: {
    options: {
      processContent: function(content) {
        return 'mixin hero(title)\n  .hero\n    .hero__inner\n      h1.hero__title #{title}\n' + content;
      }
    },
    files: {
      "path/to/dest.html": ["path/to/templates/*.jade"]
    }
  }
}
```
