### ISSUE TITLE
Update to Jade 1.11.0

### ISSUE THREAD

**Issue by ethanmick** [gruntjs/grunt-contrib-jade#142]
Can we get another update to the latest version?

Also, could there be a better way to specify the version of Jade to use? For example, being able to pass in our own version of Jade (That way, I can stay up to date with versions of Jade, while this plugin doesn't need to keep updating)?

**Comment by mathiasschopmans** [comment]
I updatet the version today, but the version tag ist still missing. The package registered on npmjs is still on 0.14.x too.

This issue should be obsolte afterwards. :)
