### ISSUE TITLE
Backslash escaping

### ISSUE THREAD

**Issue by Event-Horizon** [gruntjs/grunt-contrib-jade#143]
I'm not sure if this is the plugins issue or Jade, but it seems to destroy backslashes when converting windows file paths, and a path such as `href=".\stylesheets\font-awesome-4.3.0\css\font-awesome.min.css" ` removes the backslashes but converts the `\f` portions into a `FF` single character.

**Comment by shinnn** [comment]
> I'm not sure if this is the plugins issue or Jade

This is a Jade issue.
