### ISSUE TITLE
expand: false --> `Destination not written because compiled files were empty.`

### ISSUE THREAD

**Issue by ionox0** [gruntjs/grunt-contrib-jade#146]
Should setting `expand` to `false` cause the files to be written to a single top-level directory? For me this option leads to the following error:

```
>> Destination not written because compiled files were empty.
>> Source file "components/browse/browse.jade" not found.
>> Source file "components/chat/content.jade" not found.
>> Source file "components/chat/conversations-list.jade" not found.
...
```

**Comment by shinnn** [comment]
Questions go to http://stackoverflow.com/questions/tagged/gruntjs. Also this is not an issue with this plugin.
