### ISSUE TITLE
Change the documentation for data in options

### ISSUE THREAD

**Issue by vedantraiththa** [gruntjs/grunt-contrib-jade#149]
<img width="648" alt="screen shot 2015-10-09 at 12 32 30 pm" src="https://cloud.githubusercontent.com/assets/6807794/10399646/de651fe8-6e81-11e5-8fd6-5bfe50e86ef2.png">
Change the document for data in options because the property name used is locals instead.

**Comment by shinnn** [comment]
The code in your screenshot is totally different from the current version. https://github.com/gruntjs/grunt-contrib-jade/blob/b0b4e4b0e69629e2e147ab10b80a14deddcf6823/tasks/jade.js#L76-L81

Probably you're using an older version or a different plugin.
