### ISSUE TITLE
processContent: placeholder like <%= pkg.version %> is not replaced

### ISSUE THREAD

**Issue by barrynorman** [gruntjs/grunt-contrib-jade#152]
Maybe I do something wrong. I tried to replace a custom string by my path to a javascript file.

processContent: function(content, filename) {
                content = content.replace(/(\$\{jquery_path\})/gmi, '<%= pkg.version %>');
                return content;
}

Output: 
<script type="text/javascript" src="&lt;%= pkg.version %&gt;"></script>

Any ideas?

Thank you!

**Comment by shinnn** [comment]
https://github.com/gruntjs/grunt-contrib-jade/issues/106#issuecomment-49046102
