### ISSUE TITLE
Self-closing tags

### ISSUE THREAD

**Issue by samfearn** [gruntjs/grunt-contrib-jade#155]
I'm having a problem with self-closing tags. I have jade installed at v1.11.0 and grunt-contrib-jade installed at 0.15.0, but if I have, for instance, a meta tag in my jade file, it doesn't get closed in the outputted html.

I know this was brought up before as a problem with jade, but if i do `echo "meta" | jade` at the command prompt it gets closed fine, so it isn't just a jade problem.

Unfortunately this is causing the concat:generated from usemin to not properly read the source and so is causing all sorts of problems.

Edit: A temporary solution seems to be flushing like so:

    
    
    script(src="/scripts/test.js")

**Comment by shinnn** [comment]
grunt-contrib-jade v0.15.0 successfully compiles `meta` to `<meta/>`. Maybe other tools affect the result.
