### ISSUE TITLE
Jade renamed to Pug

### ISSUE THREAD

**Issue by DominikDitoIvosevic** [gruntjs/grunt-contrib-jade#160]
Since Jade is being renamed to Pug, will this repo change names as well?
https://github.com/pugjs/pug/issues/2184

**Comment by shinnn** [comment]
Thanks for the issue report, but just a duplicate of https://github.com/gruntjs/grunt-contrib-jade/issues/156.

Recently @vladikoff thoughtlessly closed all opened issues.
