### ISSUE TITLE
Passing a layout to extend from to the rendered template

### ISSUE THREAD

**Issue by thomasklein** [gruntjs/grunt-contrib-jade#63]
Hi! I couldn't find it in the docs and wonder if its is possible to pass to the jade task a layout which all rendered templates extend from. So basically I want to remove the 'extend myLayout' part from my templates as in

```
extend myLayout

template content...
```
and pass 'myLayout' to the grunt jade task maybe as an option parameter or even more dynamic, as a variable to the data object.

Do you see any possibility?

**Comment by shinnn** [comment]
@thomasklein You can add `extend myLayout\n` to every file with [grunt-contrib-concat](https://github.com/gruntjs/grunt-contrib-concat).
