### ISSUE TITLE
Please document tag wrapping filter includes

### ISSUE THREAD

**Issue by bmarkovic** [gruntjs/grunt-contrib-jade#80]
Because:

    script
        include script.js

results in:

     <scrip>include script.js</script>

And current Jade way of doing it:

    script
        include:js script.js

results in:

     <scrip>include:js script.js</script>

literally. at least here with grunt-contrib-jade 0.9.1 (with express) it does.

**Comment by shinnn** [comment]
Documented Here http://jade-lang.com/reference/includes/
